// Central navigation configuration for main sidebar/top nav
// Each item maps to a module key from the 3-tier subscription system

// Tier that includes this module by default
// basic = all plans, professional = pro+enterprise, enterprise = enterprise only

// ─── NAV GROUPS for top bar dropdown menus ──────────
export const NAV_GROUPS = [
  { id: "frontdesk", label: "Ön Büro & Rez.", icon: "ConciergeBell" },
  { id: "sales", label: "Satış & Gelir", icon: "TrendingUp" },
  { id: "guest", label: "Misafir & CRM", icon: "Users" },
  { id: "operations", label: "Operasyon", icon: "Building" },
  { id: "fb", label: "Restoran & F&B", icon: "Utensils" },
  { id: "backoffice", label: "Arka Ofis", icon: "Briefcase" },
  { id: "reports", label: "Raporlar", icon: "BarChart3" },
  { id: "system", label: "Kanallar & Entegrasyonlar", icon: "Settings" },
  { id: "admin", label: "Sistem Yönetimi", icon: "Shield" },
];

// Long menus are split into task-oriented sections. Keeping the section model
// in configuration makes desktop and mobile navigation tell the same story.
export const NAV_GROUP_SECTIONS = {
  frontdesk: [
    { id: "reservations", label: "Rezervasyon & Konaklama" },
    { id: "room_management", label: "Oda Yönetimi" },
    { id: "guest_services", label: "Misafir Hizmetleri" },
    { id: "daily_controls", label: "Günlük Kontroller" },
  ],
  operations: [
    { id: "daily", label: "Günlük Operasyon" },
    { id: "guest_requests", label: "Misafir Talepleri" },
    { id: "incidents", label: "Olay & Takip" },
    { id: "wellness", label: "Spa & Wellness" },
  ],
  system: [
    { id: "channels", label: "Kanal Yönetimi" },
    { id: "distribution", label: "Dağıtım & Satış" },
    { id: "integrations", label: "Entegrasyonlar" },
    { id: "setup", label: "Kurulum & Destek" },
    { id: "growth", label: "Pazarlama & Otomasyon" },
    { id: "compliance", label: "İletişim & Uyum" },
  ],
  admin: [
    { id: "centers", label: "Yönetim Merkezleri" },
    { id: "properties", label: "Oteller & İş Ortakları" },
    { id: "integrations", label: "Entegrasyon Operasyonları" },
    { id: "platform", label: "Platform Operasyonları" },
    { id: "governance", label: "Yetki, İçerik & Geliştirici" },
  ],
};

export const NAV_ITEMS = [
  // ──── STANDALONE (shown as direct buttons) ─────────
  {
    key: "dashboard",
    label: "Dashboard",
    path: "/app/dashboard",
    tier: "basic",
    group: "core",
    navGroup: null, // standalone button - always visible
  },

  // ──── TEDARİK PAZARI (B2B Supplies Marketplace) ────
  {
    key: "supplies_market",
    label: "Tedarik Pazarı",
    path: "/app/supplies-market",
    tier: "basic",
    group: "core",
    navGroup: "backoffice",
  },
  {
    key: "procurement",
    label: "Satınalma",
    path: "/app/procurement",
    tier: "basic",
    group: "core",
    navGroup: "backoffice",
  },
  {
    key: "stock_rehber",
    label: "Stok Rehberi",
    path: "/app/stock-rehber",
    tier: "basic",
    group: "core",
    navGroup: "backoffice",
  },
  {
    key: "audit_timeline",
    label: "Denetim Zaman Çizelgesi",
    path: "/audit-timeline",
    tier: "basic",
    group: "core",
    navGroup: "reports",
  },
  {
    key: "security_hub",
    label: "Güvenlik",
    path: "/security",
    tier: "basic",
    group: "core",
    navGroup: "admin",
    navSection: "centers",
  },
  {
    key: "channels_hub",
    label: "Kanallar Hub",
    path: "/channels",
    tier: "basic",
    group: "core",
    navGroup: "system",
    navSection: "channels",
    // Hub yalnızca tab seçilmediğinde (ya da sub-item'la eşleşmeyen tab'da)
    // aktif görünsün; sub-item seçildiğinde alttaki cm_dashboard /
    // channel_connections / channel_ops aktif olur.
    tabBase: ["/channels", "/app/channels"],
    tabKey: null,
  },
  {
    key: "hr_hub",
    label: "İK",
    path: "/hr",
    moduleKey: "hr",
    tier: "basic",
    group: "core",
    navGroup: "backoffice",
  },
  {
    // Task #26: acil mesaj kullanımı için adanmış rapor ekranı.
    key: "urgent_message_report",
    label: "Acil Mesaj Raporu",
    path: "/urgent-message-report",
    tier: "basic",
    group: "core",
    navGroup: "reports",
  },
  {
    // Task #35: geri alınan iç mesajlar için adanmış denetim raporu.
    key: "recalled_messages_report",
    label: "Geri Alınan Mesajlar",
    path: "/recalled-messages-report",
    tier: "basic",
    group: "core",
    navGroup: "reports",
  },
  {
    // Task #83: KVKK kapsamında resepsiyonun açtığı kimlik fotoğrafı
    // görüntülemelerini denetim için listeleyen rapor.
    key: "id_photo_view_report",
    label: "Kimlik Fotoğrafı Raporu",
    path: "/id-photo-view-report",
    tier: "basic",
    group: "core",
    navGroup: "reports",
  },
  {
    // Task #86: bekleyen kimlik fotoğraflarını listeleyen ve manuel /
    // KVKK toplu silme yapılabilen resepsiyon paneli.
    key: "id_photo_admin",
    label: "Bekleyen Kimlik Fotoğrafları",
    path: "/id-photo-admin",
    tier: "basic",
    group: "core",
    navGroup: "system",
    navSection: "compliance",
  },
  {
    // Task #28: kullanıcı bazında acil mesaj iznini açıp/kapatma sayfası.
    key: "urgent_permission_admin",
    label: "Acil Mesaj İzinleri",
    path: "/admin/urgent-permissions",
    tier: "basic",
    group: "core",
    navGroup: "system",
    navSection: "compliance",
  },
  {
    key: "contact_center_dashboard",
    label: "Çağrı Merkezi",
    path: "/app/call-center",
    tier: "basic",
    group: "core",
    navGroup: "operations",
    navSection: "daily",
    moduleKey: "contact_center",
    allowedRoles: ["call_center_agent", "supervisor", "admin", "super_admin"],
  },
  {
    // Task #282: numara -> otel/ajan eşleme yönetimi (operatör ekranı).
    key: "voice_number_mapping",
    label: "Ses Numaraları",
    path: "/admin/voice-numbers",
    tier: "basic",
    group: "core",
    navGroup: "admin",
    navSection: "platform",
    requireSuperAdmin: true,
  },

  // ──── OPERATIONS GROUP ─────────────────────────────
  {
    key: "wbe_settings",
    label: "Web Rezervasyon (WBE)",
    path: "/app/wbe-settings",
    tier: "basic",
    group: "core",
    navGroup: "system",
    navSection: "distribution",
  },
  {
    key: "reservation_calendar",
    label: "Takvim",
    path: "/app/reservation-calendar",
    moduleKey: "reservation_calendar",
    tier: "basic",
    group: "core",
    navGroup: "frontdesk",
    navSection: "reservations",
  },
  {
    key: "pms",
    label: "PMS",
    path: "/app/pms",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "frontdesk",
    navSection: "reservations",
  },
  {
    key: "housekeeping_status",
    label: "Housekeeping",
    path: "/housekeeping-status",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
  },
  {
    key: "spa_wellness",
    label: "Spa & Wellness",
    path: "/spa-wellness",
    moduleKey: "spa",
    tier: "basic",
    group: "operations",
    navGroup: "operations",
    navSection: "wellness",
  },
  {
    key: "spa_dining_packages",
    label: "Spa & Yemek Paketleri",
    path: "/spa-dining-packages",
    moduleKey: "spa",
    tier: "basic",
    group: "operations",
    navGroup: "operations",
    navSection: "wellness",
  },
  {
    key: "activity_scheduler",
    label: "Aktivite & Kaynak Rezervasyonları",
    path: "/activities",
    moduleKey: "pms",
    tier: "basic",
    group: "operations",
    navGroup: "operations",
    navSection: "wellness",
  },
  {
    key: "shift_handover",
    label: "Vardiya Devri",
    path: "/shift-handover",
    moduleKey: "pms",
    tier: "basic",
    group: "operations",
    navGroup: "operations",
    navSection: "daily",
  },
  {
    key: "early_late_pricing",
    label: "Erken/Geç Çıkış Fiyat",
    path: "/settings/early-late-pricing",
    moduleKey: "pms",
    tier: "basic",
    group: "settings",
    navGroup: "system",
    navSection: "distribution",
  },
  {
    key: "eod_report",
    label: "Gün Sonu Raporu",
    path: "/eod-report",
    moduleKey: "pms",
    tier: "basic",
    group: "operations",
    navGroup: "reports",
  },
  {
    key: "sustainability_report",
    label: "Sürdürülebilirlik Raporu",
    path: "/app/sustainability",
    tier: "basic",
    group: "operations",
    navGroup: "reports",
  },
  {
    key: "walkin",
    label: "Walk-in Check-in",
    path: "/walkin",
    // Ayrı bir üst menü kalemi değildir; Ön Büro içindeki hızlı işlemden açılır.
    hidden: true,
    moduleKey: "pms",
    tier: "basic",
    group: "operations",
    navGroup: "frontdesk",
    navSection: "reservations",
  },
  {
    key: "room_map",
    label: "Oda Planı & Atama",
    path: "/room-map",
    moduleKey: "pms",
    tier: "basic",
    group: "operations",
    navGroup: "frontdesk",
    navSection: "room_management",
  },
  {
    key: "wake_up_calls",
    label: "Uyandırma Çağrısı",
    path: "/wake-up-calls",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "frontdesk",
    navSection: "guest_services",
  },
  {
    key: "lost_found",
    label: "Kayıp Eşya",
    path: "/lost-found",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "operations",
    navSection: "guest_requests",
  },
  {
    key: "connecting_rooms",
    label: "Bağlantılı Oda Tanımları",
    path: "/suite-connecting",
    moduleKey: "pms",
    tier: "basic",
    group: "settings",
    hidden: true,
    allowedRoles: ["admin", "supervisor", "super_admin"],
  },
  {
    key: "guest_journey",
    label: "Misafir Yolculuğu",
    path: "/guest-journey",
    moduleKey: "pms",
    tier: "professional",
    group: "professional",
    navGroup: "guest",
  },
  {
    key: "operational_events",
    label: "Operasyon İzleme",
    path: "/operational-events",
    moduleKey: "pms",
    tier: "professional",
    group: "professional",
    navGroup: "operations",
    navSection: "incidents",
  },
  {
    key: "service_recovery",
    label: "Şikayet Yönetimi",
    path: "/service-recovery",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "guest",
  },

  // ──── RESERVATIONS GROUP ───────────────────────────
  {
    key: "group_bookings",
    label: "Grup Rezervasyonları",
    path: "/group-bookings-manage",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "sales",
  },
  {
    key: "block_management",
    label: "Grup Kontenjanları",
    path: "/block-management",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "sales",
  },
  {
    key: "deposit_tracking",
    label: "Depozito Takibi",
    path: "/deposit-tracking",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "sales",
  },
  {
    key: "group_folio",
    label: "Grup Folio",
    path: "/group-folio",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "sales",
  },
  {
    key: "no_show_analytics",
    label: "No-Show Analitik",
    path: "/no-show-analytics",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "reports",
  },
  {
    key: "departure_list",
    label: "Çıkış Operasyonları",
    path: "/departure-list",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "frontdesk",
    navSection: "daily_controls",
  },
  {
    key: "no_show_today",
    label: "Bekleyen Varışlar / No-Show",
    path: "/no-show-today",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "frontdesk",
    navSection: "daily_controls",
  },

  // ──── FINANCE GROUP ────────────────────────────────
  {
    key: "night_audit",
    label: "Gece Denetimi",
    path: "/night-audit",
    moduleKey: "night_audit",
    tier: "professional",
    group: "professional",
    navGroup: "frontdesk",
    navSection: "daily_controls",
  },
  {
    key: "invoices",
    label: "Fatura & Finans",
    path: "/app/invoices",
    moduleKey: "invoices",
    tier: "professional",
    group: "professional",
    navGroup: "backoffice",
  },
  {
    key: "city_ledger",
    label: "Cari Hesaplar",
    path: "/city-ledger",
    tier: "basic",
    group: "core",
    navGroup: "backoffice",
  },
  {
    key: "general_ledger",
    label: "Genel Muhasebe",
    path: "/app/general-ledger",
    moduleKey: "invoices",
    tier: "professional",
    group: "professional",
    navGroup: "backoffice",
  },
  {
    key: "bank_reconciliation",
    label: "Banka Mutabakatı",
    path: "/app/bank-reconciliation",
    moduleKey: "invoices",
    tier: "professional",
    group: "professional",
    navGroup: "backoffice",
  },
  {
    key: "fnb_costing",
    label: "F&B Maliyetleri",
    path: "/app/fnb-costing",
    moduleKey: "invoices",
    tier: "professional",
    group: "professional",
    navGroup: "fb",
  },
  {
    key: "konaklama_vergisi",
    label: "Konaklama Vergisi",
    path: "/app/konaklama-vergisi",
    moduleKey: "invoices",
    tier: "professional",
    group: "professional",
    navGroup: "backoffice",
  },
  {
    key: "mevzuat_raporlari",
    label: "Mevzuat Raporları",
    path: "/app/mevzuat-raporlari",
    moduleKey: "basic_reporting",
    tier: "professional",
    group: "professional",
    navGroup: "reports",
  },
  {
    key: "help_center",
    label: "Yardım Merkezi",
    path: "/app/help",
    tier: "starter",
    group: "starter",
    navGroup: "system",
    navSection: "setup",
  },
  {
    key: "academy",
    label: "Akademi",
    path: "/app/academy",
    tier: "addon",
    group: "core",
    navGroup: "system",
    navSection: "setup",
    moduleKey: "academy",
  },

  // ──── CHANNELS GROUP — Normal kullanici (otel personeli) ─────────
  {
    key: "cm_dashboard",
    label: "CM Dashboard",
    path: "/cm-dashboard",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "system",
    // /cm-dashboard → /channels?tab=dashboard redirect; aktif eşleşme tab ile.
    tabBase: ["/channels", "/app/channels"],
    tabKey: "dashboard",
    hidden: true,
  },
  {
    key: "go_live_readiness",
    label: "Go-Live Hazırlık",
    path: "/go-live-readiness",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "system",
    hidden: true,
  },
  {
    key: "channel_manager",
    label: "Channel Manager",
    path: "/app/channel-manager",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "system",
    hidden: true,
  },
  {
    key: "unified_rate_manager",
    label: "Fiyat & Musaitlik",
    path: "/unified-rate-manager",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "system",
    navSection: "channels",
  },
  {
    key: "room_mapping_wizard",
    label: "Oda Eslestirme Sihirbazi",
    path: "/room-mapping-wizard",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "system",
    navSection: "channels",
  },
  {
    key: "travel_agent_arap",
    label: "Acente Komisyonları",
    path: "/travel-agent-arap",
    moduleKey: "channel_manager",
    tier: "basic",
    group: "core",
    navGroup: "sales",
  },
  {
    key: "agency_management",
    label: "Acente Yönetimi",
    path: "/agency-management",
    moduleKey: "channel_manager",
    tier: "basic",
    group: "core",
    navGroup: "sales",
  },
  {
    key: "incoming_agency_contracts",
    label: "Acente Sözleşme Talepleri",
    path: "/app/incoming-agency-contracts",
    moduleKey: "channel_manager",
    tier: "basic",
    group: "core",
    navGroup: "sales",
  },
  {
    key: "agency_content",
    label: "Icerik Dagitimi",
    path: "/agency-content",
    moduleKey: "channel_manager",
    tier: "basic",
    group: "core",
    navGroup: "sales",
  },
  {
    key: "b2b_analytics",
    label: "B2B Satış Analitiği",
    path: "/b2b-analytics",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "sales",
  },
  {
    key: "report_scheduler",
    label: "Rapor Zamanlayıcı",
    path: "/report-scheduler",
    moduleKey: "basic_reporting",
    tier: "professional",
    group: "professional",
    navGroup: "reports",
  },

  // ──── CHANNELS GROUP — Admin (kanal operasyonlari) ────────────
  {
    key: "channel_ops",
    label: "Operasyon Merkezi",
    path: "/channel-ops",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "admin",
    navSection: "integrations",
    requireSuperAdmin: true,
    // /channel-ops → /channels?tab=ops redirect; aktif eşleşme tab ile.
    tabBase: ["/channels", "/app/channels"],
    tabKey: "ops",
  },
  {
    key: "channel_connections",
    label: "Kanal Baglantilari",
    path: "/channel-connections",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "system",
    // /channel-connections → /channels?tab=connections redirect; aktif eşleşme tab ile.
    tabBase: ["/channels", "/app/channels"],
    tabKey: "connections",
    hidden: true,
  },
  {
    key: "wire_failures",
    label: "Wire Failure Takibi",
    path: "/wire-failures",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "admin",
    navSection: "integrations",
    requireSuperAdmin: true,
  },
  {
    key: "ari_push",
    label: "ARI Push Engine",
    path: "/ari-push",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "admin",
    navSection: "integrations",
    requireSuperAdmin: true,
  },
  {
    key: "lockdown_dashboard",
    label: "Lockdown Dashboard",
    path: "/lockdown",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "admin",
    navSection: "integrations",
    requireSuperAdmin: true,
  },

  {
    key: "integration_hub",
    label: "Entegrasyon Merkezi",
    path: "/app/integration-hub",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "system",
    navSection: "integrations",
  },
  {
    key: "admin_hub",
    label: "Yönetim Merkezi",
    path: "/app/admin-hub",
    moduleKey: "admin_panel",
    tier: "professional",
    group: "professional",
    navGroup: "admin",
    navSection: "centers",
    requireSuperAdmin: true,
  },
  {
    key: "admin_control_panel",
    label: "Yönetim Kontrol Paneli",
    path: "/app/admin-control-panel",
    moduleKey: "channel_manager",
    tier: "professional",
    group: "professional",
    navGroup: "admin",
    navSection: "centers",
    requireSuperAdmin: true,
  },
  {
    key: "integrations_overview",
    label: "Entegrasyon Genel Bakış",
    path: "/admin/integrations-overview",
    moduleKey: "admin_panel",
    tier: "professional",
    group: "professional",
    navGroup: "admin",
    navSection: "centers",
    requireSuperAdmin: true,
  },
  {
    key: "integration_credentials",
    label: "Entegrasyon Anahtarları",
    path: "/admin/integration-credentials",
    moduleKey: "admin_panel",
    tier: "professional",
    group: "professional",
    navGroup: "admin",
    navSection: "integrations",
    requireSuperAdmin: true,
  },
  {
    key: "capx_integration",
    label: "CapX Entegrasyonu",
    path: "/admin/capx-integration",
    moduleKey: "admin_panel",
    tier: "professional",
    group: "professional",
    navGroup: "admin",
    navSection: "integrations",
    requireSuperAdmin: true,
  },

  // ──── REPORTS GROUP ────────────────────────────────
  {
    key: "reports_basic",
    label: "Raporlar",
    path: "/app/raporlar",
    moduleKey: "basic_reporting",
    tier: "basic",
    group: "core",
    navGroup: "reports",
  },
  {
    key: "report_builder",
    label: "Rapor Oluşturucu",
    path: "/app/rapor-olusturucu",
    moduleKey: "reports",
    tier: "professional",
    group: "professional",
    navGroup: "reports",
  },

  // ──── ADVANCED GROUP ───────────────────────────────
  {
    key: "revenue_hub",
    label: "Gelir Merkezi",
    path: "/app/revenue-hub",
    moduleKey: "revenue_management",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "sales",
  },
  {
    key: "ai_zeka",
    label: "AI & Zeka",
    path: "/app/ai",
    tier: "enterprise",
    group: "advanced",
    moduleKey: "ai",
    navGroup: "system",
    navSection: "growth",
  },
  {
    key: "mailing",
    label: "E-posta Pazarlama",
    path: "/app/mailing",
    tier: "basic",
    group: "core",
    navGroup: "system",
    navSection: "growth",
  },
  {
    key: "onboarding_wizard",
    label: "Kurulum Sihirbazı",
    path: "/app/onboarding",
    tier: "basic",
    group: "core",
    navGroup: "system",
    navSection: "setup",
  },
  {
    key: "module_store",
    label: "Modül Pazarı",
    path: "/app/module-store",
    tier: "basic",
    group: "core",
    navGroup: "system",
    navSection: "setup",
  },
  {
    key: "pci_compliance",
    label: "PCI-DSS Uyum",
    path: "/app/compliance/pci",
    tier: "basic",
    group: "core",
    navGroup: "system",
    navSection: "compliance",
  },
  {
    key: "webhook_outbox_admin",
    label: "Outbox & Webhook DLQ",
    path: "/admin/webhook-outbox",
    tier: "professional",
    group: "core",
    navGroup: "admin",
    navSection: "platform",
    requireSuperAdmin: true,
  },
  {
    key: "early_warning_dashboard",
    label: "Erken Uyarı Motoru",
    path: "/admin/early-warning",
    tier: "professional",
    group: "core",
    navGroup: "admin",
    navSection: "platform",
    requireSuperAdmin: true,
  },
  {
    key: "module_discovery",
    label: "Modül Keşfi",
    path: "/admin/module-discovery",
    tier: "basic",
    group: "core",
    navGroup: "admin",
    navSection: "platform",
    requireSuperAdmin: true,
  },
  {
    key: "xchange",
    label: "Xchange (SXI)",
    path: "/app/xchange",
    tier: "basic",
    group: "core",
    navGroup: "system",
    navSection: "integrations",
  },
  {
    key: "pos_dashboard",
    label: "Satış Noktası (POS)",
    path: "/pos",
    moduleKey: "pms",
    tier: "basic",
    group: "core",
    navGroup: "fb",
  },
  {
    key: "mice",
    label: "MICE & Banquet",
    path: "/app/mice",
    moduleKey: "mice",
    tier: "basic",
    group: "core",
    navGroup: "fb",
  },
  {
    key: "afsadakat",
    label: "Sadakat & Inbox",
    path: "/app/afsadakat",
    moduleKey: "af_sadakat",
    tier: "basic",
    group: "core",
    navGroup: "guest",
  },
  {
    key: "messaging_dashboard",
    label: "Mesajlaşma Merkezi",
    path: "/messaging-dashboard",
    moduleKey: "pms",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "guest",
  },
  {
    key: "analitik_raporlar",
    label: "Analitik & Raporlar",
    path: "/app/analitik",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "reports",
  },

  // ──── INFRASTRUCTURE GROUP ─────────────────────────
  // Moved from channels: platform-level ops tools
  {
    key: "control_plane",
    label: "Control Plane",
    path: "/control-plane",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
    requireSuperAdmin: true,
  },
  {
    key: "runtime_cockpit",
    label: "Runtime Cockpit",
    path: "/runtime-cockpit",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
    requireSuperAdmin: true,
  },
  {
    key: "incident_panel",
    label: "Incident Panel",
    path: "/incidents",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
    requireSuperAdmin: true,
  },
  {
    key: "system_health",
    label: "System Health",
    path: "/system-health",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },
  {
    key: "security_hardening",
    label: "Güvenlik & Güçlendirme",
    path: "/security-hardening",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },
  {
    key: "encryption_management",
    label: "Şifreleme Yönetimi",
    path: "/encryption-management",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },
  {
    key: "production_golive",
    label: "Production Go-Live",
    path: "/production-golive",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
  },

  // ──── INFRASTRUCTURE — Hidden (deep platform ops, direct URL still works) ──
  {
    key: "data_pipeline",
    label: "Data Pipeline",
    path: "/data-pipeline",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
    hidden: true,
  },
  {
    key: "event_bus",
    label: "Event Bus",
    path: "/event-bus",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
    hidden: true,
  },
  {
    key: "runtime_infrastructure",
    label: "Runtime Infrastructure",
    path: "/runtime-infrastructure",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
    hidden: true,
  },
  {
    key: "platform_scaling",
    label: "Platform Scaling",
    path: "/platform-scaling",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
    hidden: true,
  },
  {
    key: "enterprise_live",
    label: "Enterprise Live",
    path: "/enterprise-live",
    moduleKey: "advanced_analytics",
    tier: "enterprise",
    group: "enterprise",
    navGroup: "infrastructure",
    hidden: true,
  },

  // ──── STANDALONE: Settings ─────────────────────────
  {
    key: "settings",
    label: "Ayarlar",
    path: "/app/settings",
    tier: "basic",
    group: "core",
    navGroup: null, // standalone button - always visible
  },

  // ──── HIDDEN ───────────────────────────────────────
  {
    key: "marketplace",
    label: "Marketplace",
    path: "/app/marketplace",
    moduleKey: "marketplace",
    tier: "enterprise",
    group: "enterprise",
    navGroup: null,
    hidden: true,
  },

  // ──── SUPER ADMIN ONLY ─────────────────────────────
  {
    key: "admin_tenants",
    label: "Otel Yönetimi",
    path: "/admin/tenants",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: "admin",
    navSection: "properties",
  },
  {
    key: "admin_vendors",
    label: "Tedarikci Yönetimi",
    path: "/admin/vendors",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: "admin",
    navSection: "properties",
  },
  {
    key: "admin_module_report",
    label: "Modul Raporu",
    path: "/admin/module-report",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: "admin",
    navSection: "properties",
  },
  {
    key: "admin_leads",
    label: "Leads",
    path: "/app/admin/leads",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: "admin",
    navSection: "properties",
  },
  {
    key: "governance",
    label: "Governance",
    path: "/admin/governance",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: "admin",
    navSection: "governance",
  },
  {
    key: "site_content",
    label: "Landing İçeriği",
    path: "/admin/site-content",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: "admin",
    navSection: "governance",
  },
  {
    key: "quick_id_settings",
    label: "Kimlik Tarama (Quick-ID)",
    path: "/admin/quick-id",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: "admin",
    navSection: "governance",
  },
  {
    key: "room_qr_requests",
    label: "Oda QR Merkezi",
    path: "/app/room-requests",
    group: "operations",
    navGroup: "operations",
    navSection: "guest_requests",
    icon: "MessageSquare",
    moduleKey: "room_qr_requests",
    tier: "basic",
  },
  {
    key: "room_qr_codes",
    label: "Oda QR Kodları",
    path: "/admin/room-qr-codes",
    group: "admin",
    navGroup: "admin",
    navSection: "properties",
    icon: "QrCode",
    moduleKey: "room_qr_requests",
    tier: "basic",
    allowedRoles: ["admin", "super_admin"],
  },
  {
    key: "api_docs",
    label: "API Dokumantasyon",
    path: "/b2b/docs",
    requireSuperAdmin: true,
    group: "admin",
    navGroup: "admin",
    navSection: "governance",
  },
];

// Legacy compatibility
export const PMS_LITE_NAV_KEYS = new Set([
  'dashboard',
  'reservation_calendar',
  'pms',
  'reports_basic',
  'settings',
]);
